/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.random.Random
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import kotlin.test.fail

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test fun randoFail() {
        val randomNumber = Random.nextInt()
        assertEquals(randomNumber, randomNumber + 1)
    }

    @Test fun alwaysTrue() {
        assertTrue { true }
    }

    @Test fun alwaysFail() {
        System.getenv("fail")?.let {
            fail(message = "app failed as expected")
        }
    }
}
